### ISSUE TITLE
Program crashes on startup

### ISSUE THREAD

**Issue by ghost** [darkoverlordofdata/kitty-cat-lock#1]
Hey, I tried to build and run catlock but it immediately crashes with an address boundary error. I poked a bit at the code and it seems that in `application_fonts` function the line `this->fontname = strdup(name);` is not working correctly, since trying to access `this->fontname` is what the crash originates from. I don't know enough C++ to debug further, so hoping you can help figure out this issue

**Comment by darkoverlordofdata** [comment]
Thanks for your interest in this project. I was expecting a different issue (I've updated the ‘known issues’ section of the readme) 

I can reproduce this issue when I compile with gcc (default compiler on Linux). The code originates on BSD, and I prefer clang for a compiler.  

You could try installing clang (sudo apt install clang) OR wait a day and I’ll get this working with gcc.

**Comment by ghost** [comment]
Oh, I see. Didn't realize this is targeted towards BSD. Either way, I installed clang and had the same issue; was it working for you with clang on Linux?

**Comment by darkoverlordofdata** [comment]
The project was started on bsd, but I run it daily on ubuntu. There is a known issue with strdup and gcc, that was my first thought.  But if it crashes even after clang is installed... there’s something else. It’s a work in progress. 

The issue maybe be that the theme name is used as a folder name to find your wallpaper - it the folders not there, it crashes. I run another program to synch my wallpaper with bing. But you can also just use your current wallpaper. So let's try this from the start, and make sure all the pieces are installed correctly. 

Make sure you have image magic – if ‘which convert’ shows nothing, ‘sudo apt install imagemagick’  

I have catlock compiling now with gcc, and finished up some other fixes. So, 

Re clone from github. 
```
git clone https://github.com/darkoverlordofdata/kitty-cat-lock.git
cd kitty-cat-lock 
./configure 
cd build 
make 
cd .. 
bash wallpaper/copy.sh path/to/your/wallpaper.jpg screen_width screen_height 
```

Then test it: 

```
./catlock --theme wallpaper 
```
It should run and exit when you hit return. 

After install, run as 

```
catlock –theme wallpaper –pin 123 
```

Then 123 will unlock it. 

I’ve updated the readme instructions; I hope they are clearer now.

**Comment by ghost** [comment]
It works now! I do still get a SIGSEGV, but now it's after unlocking, so it's less of an issue. Anyway, thanks for your help!

**Comment by darkoverlordofdata** [comment]
Ah - that is a bug. in application_dispose():
```
free(this->script[3]);
``` 
should be script[2]; it doesn't trigger an error on my desktop, but it seems it should. That is what undefined behaviour will do for you:) 
This bug has been corrected.
